### ISSUE TITLE
spec: Come up with a better sender public key header.

### ISSUE THREAD

**Issue by Yawning** [katzenpost/mixnet_uprising#20]
The spec(s) currently specify variations of `X-Panoramix-Sender-Identity-Key` as the sender public key header.

This needs to be formalized sooner rather than later, and as far as I can tell needs the following adjustments:

 * Rename to be in the `X-Katzenpost` namespace.
 * Shortened down such that the full header will be under 78 bytes (excluding the trailing CR/LF), to avoid wrapping (See: RFC 5322 2.1.1).

**Comment by meskio** [comment]
X-Katzenpost-Identity-Key?

We might want in the future to be able to gossip keys of other recipients in a multiparty conversation. If we don't add addresses to this header might get confusing.

X-Katzenpost-Sender-Key?

In the context of a header I think is obvious that the key is an identity key.

**Comment by Yawning** [comment]
I think `X-Katzenpost-Sender-Key` is reasonable.

I would say that `X-Katzenpost-Sender-Identity-Key` is also ok, but it annoys me that the last 3 characters of the Base64 encoded public key end up on a new line.

**Comment by moba** [comment]
Why not without the `-Key`? It is obvious from the context that it is a key, representing a sender (identity), so it is kind of redundant.

**Comment by Yawning** [comment]
`X-Katzenpost-Sender` is the most concise and to the point (and is certainly going to be the most common).  Anything that wants to add more headers with keys will need to disambiguate themselves somehow anyway, so those can be the things with the longer headers.

**Comment by Yawning** [comment]
By fiat, this now will be `X-Katzenpost-Sender`.
