### ISSUE TITLE
make a chutney-like tool for katzenpost local deploy

### ISSUE THREAD

**Issue by david415** [katzenpost/mixnet_uprising#23]
Currently our work flow involves using a demotools kimchi branch variation to test new mixnet features whereas if we had a chutney-like tool we could just use that instead and we'd get way more code coverage... testing code in the Main functions. Further, having a chutney like tool would be useful for other things, for example testing client features that cannot execute in golang but from another language client... integration testing of other language bindings and user interfaces.

For extra credit, get travis to run the full integration test by deploying an entire mix network on their puny travis VM and run a series of tests via Alice and Bob sending each other messages from different Providers on the "network".

**Comment by Yawning** [comment]
I guess? I'd rather people improved kimchi instead.  The only difference between the main functions of the various daemons and what kimchi does is the daemons load a config file.

**Comment by david415** [comment]
OK. closing ticket.
