### ISSUE TITLE
add PostDescriptor command to core/wire/commands

### ISSUE THREAD

**Issue by david415** [katzenpost/mixnet_uprising#25]
Eliminate http from mixes? Mixes could of course use the link layer protocol instead of http to put their descriptors.

**Comment by Yawning** [comment]
That's what I was planning on doing for: https://github.com/katzenpost/authority/issues/12

The authority right now can/will return `Bad Request`, `Conflict`, `Forbidden` and `OK`.

**Comment by Yawning** [comment]
The code side of this is done, I refrained from updating the spec because David's working on it actively.  The two extra commands and status codes should be self explanatory.

**Comment by Yawning** [comment]
The spec side of this has been done by @david415, so I'm calling this closed.
