### ISSUE TITLE
How do we deal with mixnet topology changes?

### ISSUE THREAD

**Issue by moba** [katzenpost/mixnet_uprising#37]
We discussed how we want to keep the mixnet topology mostly stable, and NOT randomize every epoch. Any change of topology will partition the anonymity set.

In practice, we will have to change the topology at least every time a mix is added or removed (permanently or temporarily because of downtime).

Claudia wants to think about this a bit more, which is why I am putting this down as a note.

Another open issue is how we deal with intermittent connectivity problems. Claudia did like the idea of shorter epoch times to at least reduce the problem. We might still need "consensus amendments" in-between epochs, but that requires more thinking.

**Comment by Yawning** [comment]
For what it's worth (and I mentioned this when I spoke to Claudia/David briefly earlier), the current authority already attempts to maintain a stable network topology, and has for a while.

https://github.com/katzenpost/authority/commit/59aafb159a8c2f5c558659b451ed0bc2a78016fc

**Comment by mixmasala** [comment]
Updating this ticket since it's still open. Authorities (voting) inherit the topology from previous consensus documents, if available. New mixes get inserted into layers, round-robin style, sorted using a deterministic RNG seeded with the shared random value.

**Comment by david415** [comment]
are there any more tasks needed to satisfy this ticket? i was under the impression that all the work was done. although we don't yet have thorough testing it is believed that the voting pki operates correctly and only rerandomized the topology when a threshold unbalanced condition is met.

**Comment by mixmasala** [comment]
I believe the ticket is phrased as a question and we have answered it.
