### ISSUE TITLE
Increase protection of message transport anonymity

### ISSUE THREAD

**Issue by PowerPress** [katzenpost/mixnet_uprising#54]
This is a simple fix I would like to see considered for implementation. Have all providers, clients and certificate authorities utilize Tor Hidden services to communicate with each other. Tor will help provide additional cover traffic and assistance in keeping location anonymity.

Additionally by the client creating a Tor Hidden Service to receive the ACK response of the client with both utilize the hidden service design it prevents any of the providers themselves knowing the direct IP address of the sender. This will require much more resources for a global adversary to compromise the message.

**Comment by Yawning** [comment]
A) Most but not all things support using any transport.
B) Hiding usage of Katzenpost is outside the threat model of the design, and something that at least I consider to be an intractable open research question.
