### ISSUE TITLE
create mix operator mailing list

### ISSUE THREAD

**Issue by david415** [katzenpost/mixnet_uprising#60]
we need a mailing list to coordinate releases with mix operators... and probably for other related operational issues. please make us another mailing list and we'll get this train moving.

**Comment by moba** [comment]
I created a list called "katzenops" for this now: anyone can subscribe, only subscribers can post, public archive. Let me know if you read this and want to help manage it and I will add you as a moderator.

https://lists.mixnetworks.org/listinfo/katzenops

**Comment by moba** [comment]
Oh and honestly I am not sure if we need a second list at this point. We could just discuss operator issues on the general katzenpost mailing list for now, it's not like it has heavy traffic.
