### ISSUE TITLE
write an autoresponder client

### ISSUE THREAD

**Issue by david415** [katzenpost/mixnet_uprising#64]
< Valodim[m]> a python thing that's basically a loop "wait for message - when message comes in, reply to sender of that message" sounds exactly right

**Comment by Valodim** [comment]
(copying from dup #65)

For demonstration purposes, we should have a simple autoresponder bot. Roughly:

```
funnyquotes[] = [ "mixnets are great!", "did you know mixnets are different from tor?" ]
while (true) {
  sender, msg = receive();
  send(sender, "you sent a msg to me, yay!" + funnyquotes[random.int])
}
```

Bonus points if this can run in a log viewer and gives enough output for users to see what's happening. It's very hard to convey to the user that anything more than emails being sent is going on, for demonstration purposes we should show some internals. This is a nice way to do that.

**Comment by david415** [comment]
done. https://github.com/katzenpost/tools/tree/master/pong
