### ISSUE TITLE
add http registration endpoint for checking name availability

### ISSUE THREAD

**Issue by Valodim** [katzenpost/mixnet_uprising#66]

**Comment by david415** [comment]
it seems like there should be a better way to do this. furthermore when we add code into the mix server first we decide if the code actually belongs outside the mix server in another repo or something.

**Comment by Valodim** [comment]
there are certainly better ways to do this. kali implemented one in his registration thing in February. the question is though, can we get it done today?

**Comment by david415** [comment]
@Valodim what did kali implement?
