### ISSUE TITLE
setup a test network with publicly exposed logs

### ISSUE THREAD

**Issue by david415** [katzenpost/mixnet_uprising#7]
test network for the mixnet researchers to play with

**Comment by moba** [comment]
It would be nice to display the logs of the testbed providers and mixnet nodes on one screen, and have it dynamically follow the log so you can watch what is going on.

http://logio.org/ looks interesting but I don't know it at all and their demo is down.

As a first and straightforward step, we could expose the logs on each machine via http (and then build something on top of that).

**Comment by Yawning** [comment]
Note that real users should never have access to this sort of network because the `DEBUG` logging level on the provider and mixes totally destroys anonymity.

**Comment by david415** [comment]
agreed.

**Comment by moba** [comment]
So, we have a testbed log viewer now at http://logviewer.katzenpost.mixnetworks.org/ (yes, HTTP).
