### ISSUE TITLE
add client that does Signal Double Ratchet

### ISSUE THREAD

**Issue by david415** [katzenpost/mixnet_uprising#85]
Before we write a mixnet Signal Double Ratchet chat application we must write a Signal Double Ratchet-"comm channel" library. That is, we must use the new "multispool" service to form a bidirectional communications channel between two clients.

**Comment by cloehle** [comment]
[Channels library](https://github.com/katzenpost/channels)

**Comment by david415** [comment]
my thinking since then has changed. catshadow uses trial decryption and therefore the channels library i wrote is useless for this use case. closing this ticket for now.
